### ISSUE TITLE
Changes in Edline Site

### ISSUE THREAD

**Issue by rydohg** [Esaych/edline-api#1]
In the year since the last commit it seems that Edline changed their site structure. For example, the class edlDocViewContents doesn't exist anymore and i'm now not able to get grades or teacher names (course names still are there tho)

**Comment by Esaych** [comment]
Hmm, it still works for Edline on my account. Could you upload a pastebin of the source of your Edline where the edlDocViewContents doesn't exist? Thank you.

**Comment by rydohg** [comment]
http://pastebin.com/e3mdXKj2

**Comment by Esaych** [comment]
After analyzing your paste, there seems to be a navigation error

My API will first:
-parse your main Edline page for your courses, store them into the course object
-within the course object parse for grades.

You have given me the main Edline page of your school with your individual courses included, but if it errors in the Grades object, then the program has failed to find your grade report.

In order to find your grade report, the API follows this process:
1) Navigate to 

> https://www.edline.net/pages/*SCHOOL*/*URL_in_course_object*/Current_Assignments_Report

2) this automatically should show your grades in an iframe
3) find the iframe with your grade report, and open the content directly.

Please, send me a paste of:
1. your school Edline page
2. a sample course assignments report for a course, along with the URL used to open it
3. possibly the source iframe if you can find it in the source code

**Comment by rydohg** [comment]
I've looked into how my high schools Edline page is setup and I don't think I can get the info I want mainly because there is no grade report under Current_Assignments_Report for any class. All of the grade reports are under something like 04_11_16_SEMESTER_2_Average. I might be able to get a list of the names of the grade reports if I used the javascript function triggered when you click on the "Private Reports" button under the menu but I couldn't do that with Jsoup and I don't have the time to mess with that (at least until summer break). For now i'm taking a break from coding cause of testing like the FSA Writing (that we started today) and all the EOCs and such.
